; ============================================================================
; PHP-FPM pool for the WebPanel management UI itself
; ----------------------------------------------------------------------------
[webpanel]
user = webpanel
group = webpanel

listen = /run/php-fpm/panel.sock
listen.owner = nginx
listen.group = nginx
listen.mode = 0660

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 1000

php_admin_value[open_basedir] = /usr/local/webpanel/panel:/tmp
php_admin_value[upload_tmp_dir] = /tmp
php_admin_value[session.save_path] = /usr/local/webpanel/panel/data/sessions
php_admin_value[error_log] = /www/wwwlogs/panel.php-error.log
php_admin_value[memory_limit] = 256M
php_admin_value[upload_max_filesize] = 1024m
php_admin_value[post_max_size] = 1028m
php_admin_value[date.timezone] = Asia/Shanghai
